analysis_path: "."
input_ria_path: .babs/input_ria
output_ria_path: .babs/output_ria
input_datasets:
  raw:
    origin_url: /home/f008q9c_dartmouth_edu/STAMPED-dl_morphometrics_biases/studies/simbids/sourcedata/raw
    path_in_babs: sourcedata/raw
    is_zipped: false
    required_files:
      - "anat/*_T1w.nii*"
cluster_resources:
  interpreting_shell: /bin/bash
  customized_text: "#SBATCH --partition=cpu"
  number_of_cpus: 1
  hard_memory_limit: 4096M
  hard_runtime_limit: "00:15:00"
script_preamble: |
  source "$HOME/.bashrc"
  eval "$(pixi shell-hook --locked --environment babs --manifest-path "$HOME/STAMPED-dl_morphometrics_biases/pixi.toml")"
job_compute_space: /scratch4/workspace/f008q9c_dartmouth_edu-stamped-phase3/jobs
singularity_args:
  - --containall
  - --writable-tmpfs
  - --net
  - --network
  - none
bids_app_args:
  --bids-app: fmriprep
  $SUBJECT_SELECTION_FLAG: --participant-label
  --stop-on-first-crash: ""
  --anat-only: ""
  --n-cpus: "1"
  --omp-nthreads: "1"
  --mem-mb: "3072"
  -vv: ""
all_results_in_one_zip: true
zip_foldernames:
  fmriprep_anat: simbids-0-1-dev27
alert_log_messages:
  stdout:
    - "Cannot allocate memory"
    - "SimBIDS failed"
